### ISSUE TITLE
C99 required..

### ISSUE THREAD

**Issue by jhallen** [dhoerl/EngineeringNotationFormatter#3]
The requirement for fpclassify which is a C99 function was giving me trouble.  Some old systems don't have it!

I wrote a string based solution which does not requite this if you are interested: [https://github.com/jhallen/joes-sandbox/blob/master/math/eng.c](https://github.com/jhallen/joes-sandbox/blob/master/math/eng.c).

Some other things:
- it would be nice if it shows all digits, not just a fixed number (mine does this: trims leading and trailing zeros).
- it would be nice if you could shift the decimal point 3 places up or down.  Calculators can do this.

**Comment by dhoerl** [comment]
Beauty of open source is you can take what's there and run with it. I doubt I will do any more additions to this code so suggests you add these features to your version.
