### ISSUE TITLE
loss of precision / incorrect rounding?

### ISSUE THREAD

**Issue by janwilmans** [dhoerl/EngineeringNotationFormatter#4]
![image](https://user-images.githubusercontent.com/5933444/43772222-b3b22914-9a41-11e8-92f9-750650409f1e.png)

In the image it shows 385.0e-15 instead of 385.**7**e-15 !

**Comment by dhoerl** [comment]
Will look at it in a few days - it’s been a long time since I last touched this code. Do the unit tests still pass?

**Comment by janwilmans** [comment]
I have no idea, i just noticed that there is an odd rounding error in the
screenshot on the main page

**Comment by dhoerl** [comment]
@janwilmans I know its been a while - I just noticed this report again. The issue was in the Stepper UI code not the core formatter, and its been fixed (and the project updated to Xcode 11)
